name: matematicadivertida
description: "Jogo educativo de matemática gamificado em Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔊 Áudio para efeitos sonoros e trilha
  audioplayers: ^6.6.0

  # 💾 Persistência de dados para salvar recordes (ADICIONE ESTA LINHA)
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/