// File generated by FlutterFire CLI and manually adjusted.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz4iH5fKFHmeBHhaScAN9SlTRJNJZNxwk',
    appId: '1:5577210485:web:00bfb033bbdc2ee11d963c',
    messagingSenderId: '5577210485',
    projectId: 'matematica-divertida-b285a',
    authDomain: 'matematica-divertida-b285a.firebaseapp.com',
    storageBucket: 'matematica-divertida-b285a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs5vmQlPeB0lkjJMC3084Sm-YkgpH17rQ',
    appId: '1:5577210485:android:0eadd0b190a031d01d963c',
    messagingSenderId: '5577210485',
    projectId: 'matematica-divertida-b285a',
    storageBucket: 'matematica-divertida-b285a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg20D8t4nMWoBenTAv7VfGepO1_3T9B3M',
    appId: '1:5577210485:ios:553044ba6d4655dc1d963c',
    messagingSenderId: '5577210485',
    projectId: 'matematica-divertida-b285a',
    storageBucket: 'matematica-divertida-b285a.firebasestorage.app',
    iosBundleId: 'com.example.matematicadivertida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg20D8t4nMWoBenTAv7VfGepO1_3T9B3M',
    appId: '1:5577210485:ios:553044ba6d4655dc1d963c',
    messagingSenderId: '5577210485',
    projectId: 'matematica-divertida-b285a',
    storageBucket: 'matematica-divertida-b285a.firebasestorage.app',
    iosBundleId: 'com.example.matematicadivertida',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz4iH5fKFHmeBHhaScAN9SlTRJNJZNxwk',
    appId: '1:5577210485:web:00bfb033bbdc2ee11d963c',
    messagingSenderId: '5577210485',
    projectId: 'matematica-divertida-b285a',
    authDomain: 'matematica-divertida-b285a.firebaseapp.com',
    storageBucket: 'matematica-divertida-b285a.firebasestorage.app',
  );
}