// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz4iH5fKFHmeBHhaScAN9SlTRJNJZNxwk',
    appId: '1:5577210485:web:1057995e19dc535b1d963c',
    messagingSenderId: '5577210485',
    projectId: 'matematica-divertida-b285a',
    authDomain: 'matematica-divertida-b285a.firebaseapp.com',
    storageBucket: 'matematica-divertida-b285a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs5vmQlPeB0lkjJMC3084Sm-YkgpH17rQ',
    appId: '1:5577210485:android:0eadd0b190a031d01d963c',
    messagingSenderId: '5577210485',
    projectId: 'matematica-divertida-b285a',
    storageBucket: 'matematica-divertida-b285a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg20D8t4nMWoBenTAv7VfGepO1_3T9B3M',
    appId: '1:5577210485:ios:553044ba6d4655dc1d963c',
    messagingSenderId: '5577210485',
    projectId: 'matematica-divertida-b285a',
    storageBucket: 'matematica-divertida-b285a.firebasestorage.app',
    androidClientId: '5577210485-7a182kq109mmgbh16t5ou50hbehbqssi.apps.googleusercontent.com',
    iosClientId: '5577210485-oshms553jl24d7r5ftgersp3k9aiti30.apps.googleusercontent.com',
    iosBundleId: 'com.example.matematicadivertida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg20D8t4nMWoBenTAv7VfGepO1_3T9B3M',
    appId: '1:5577210485:ios:553044ba6d4655dc1d963c',
    messagingSenderId: '5577210485',
    projectId: 'matematica-divertida-b285a',
    storageBucket: 'matematica-divertida-b285a.firebasestorage.app',
    androidClientId: '5577210485-7a182kq109mmgbh16t5ou50hbehbqssi.apps.googleusercontent.com',
    iosClientId: '5577210485-oshms553jl24d7r5ftgersp3k9aiti30.apps.googleusercontent.com',
    iosBundleId: 'com.example.matematicadivertida',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz4iH5fKFHmeBHhaScAN9SlTRJNJZNxwk',
    appId: '1:5577210485:web:783168a65c3704b91d963c',
    messagingSenderId: '5577210485',
    projectId: 'matematica-divertida-b285a',
    authDomain: 'matematica-divertida-b285a.firebaseapp.com',
    storageBucket: 'matematica-divertida-b285a.firebasestorage.app',
  );

}