// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

const _placeholder = 'REPLACE_WITH_YOUR_VALUE';

const _firebaseProjectId = 'matematica-divertida-b285a';
const _firebaseStorageBucket = 'matematica-divertida-b285a.firebasestorage.app';
const _firebaseAuthDomain = 'matematica-divertida-b285a.firebaseapp.com';
const _firebaseAndroidClientId = '5577210485-7a182kq109mmgbh16t5ou50hbehbqssi.apps.googleusercontent.com';
const _firebaseIosClientId = '5577210485-oshms553jl24d7r5ftgersp3k9aiti30.apps.googleusercontent.com';
const _firebaseAndroidApiKey = 'AIzaSyAs5vmQlPeB0lkjJMC3084Sm-YkgpH17rQ';
const _firebaseAndroidAppId = '1:5577210485:android:0eadd0b190a031d01d963c';
const _firebaseAndroidMessagingSenderId = '5577210485';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: 'AIzaSyCz4iH5fKFHmeBHhaScAN9SlTRJNJZNxwk'),
    appId: String.fromEnvironment('FIREBASE_WEB_APP_ID', defaultValue: '1:5577210485:web:1057995e19dc535b1d963c'),
    messagingSenderId: String.fromEnvironment('FIREBASE_WEB_MESSAGING_SENDER_ID', defaultValue: '5577210485'),
    projectId: String.fromEnvironment('FIREBASE_WEB_PROJECT_ID', defaultValue: _firebaseProjectId),
    authDomain: String.fromEnvironment('FIREBASE_WEB_AUTH_DOMAIN', defaultValue: _firebaseAuthDomain),
    storageBucket: String.fromEnvironment('FIREBASE_WEB_STORAGE_BUCKET', defaultValue: _firebaseStorageBucket),
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: _firebaseAndroidApiKey),
    appId: String.fromEnvironment('FIREBASE_ANDROID_APP_ID', defaultValue: _firebaseAndroidAppId),
    messagingSenderId: String.fromEnvironment('FIREBASE_ANDROID_MESSAGING_SENDER_ID', defaultValue: _firebaseAndroidMessagingSenderId),
    projectId: String.fromEnvironment('FIREBASE_ANDROID_PROJECT_ID', defaultValue: _firebaseProjectId),
    storageBucket: String.fromEnvironment('FIREBASE_ANDROID_STORAGE_BUCKET', defaultValue: _firebaseStorageBucket),
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: _placeholder),
    appId: String.fromEnvironment('FIREBASE_IOS_APP_ID', defaultValue: _placeholder),
    messagingSenderId: String.fromEnvironment('FIREBASE_IOS_MESSAGING_SENDER_ID', defaultValue: _placeholder),
    projectId: String.fromEnvironment('FIREBASE_IOS_PROJECT_ID', defaultValue: _firebaseProjectId),
    storageBucket: String.fromEnvironment('FIREBASE_IOS_STORAGE_BUCKET', defaultValue: _firebaseStorageBucket),
    androidClientId: String.fromEnvironment('FIREBASE_IOS_ANDROID_CLIENT_ID', defaultValue: _firebaseAndroidClientId),
    iosClientId: String.fromEnvironment('FIREBASE_IOS_IOS_CLIENT_ID', defaultValue: _firebaseIosClientId),
    iosBundleId: String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID', defaultValue: 'com.example.matematicadivertida'),
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_MACOS_API_KEY', defaultValue: _placeholder),
    appId: String.fromEnvironment('FIREBASE_MACOS_APP_ID', defaultValue: _placeholder),
    messagingSenderId: String.fromEnvironment('FIREBASE_MACOS_MESSAGING_SENDER_ID', defaultValue: _placeholder),
    projectId: String.fromEnvironment('FIREBASE_MACOS_PROJECT_ID', defaultValue: _firebaseProjectId),
    storageBucket: String.fromEnvironment('FIREBASE_MACOS_STORAGE_BUCKET', defaultValue: _firebaseStorageBucket),
    androidClientId: String.fromEnvironment('FIREBASE_MACOS_ANDROID_CLIENT_ID', defaultValue: _firebaseAndroidClientId),
    iosClientId: String.fromEnvironment('FIREBASE_MACOS_IOS_CLIENT_ID', defaultValue: _firebaseIosClientId),
    iosBundleId: String.fromEnvironment('FIREBASE_MACOS_BUNDLE_ID', defaultValue: 'com.example.matematicadivertida'),
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WINDOWS_API_KEY', defaultValue: _placeholder),
    appId: String.fromEnvironment('FIREBASE_WINDOWS_APP_ID', defaultValue: _placeholder),
    messagingSenderId: String.fromEnvironment('FIREBASE_WINDOWS_MESSAGING_SENDER_ID', defaultValue: _placeholder),
    projectId: String.fromEnvironment('FIREBASE_WINDOWS_PROJECT_ID', defaultValue: _firebaseProjectId),
    authDomain: String.fromEnvironment('FIREBASE_WINDOWS_AUTH_DOMAIN', defaultValue: _firebaseAuthDomain),
    storageBucket: String.fromEnvironment('FIREBASE_WINDOWS_STORAGE_BUCKET', defaultValue: _firebaseStorageBucket),
  );

}